#!/usr/bin/env python3
r"""
reorganize.py -- rename and merge graph nodes, rewriting every link that points
at them.

A node rename isn't just a folder rename: every transcript carries a
`project: "[[../../<Node> - Index|<Node>]]"` frontmatter line, summary notes
carry a one-level-shallower variant, and attachments carry a three-level one.
Footers and index files are regenerated by reindex.py, but frontmatter is not,
so it has to be rewritten here.

Merging additionally has to resolve collisions. Two nodes each holding a
`Project Memory - Personal.md` can't both keep the name; the incoming one is
renamed using the label supplied in MOVES.

  py -3 reorganize.py [--vault <path>] [--dry-run]

Edit MOVES below, run with --dry-run, read it, then run for real. Afterwards run
reindex.py.
"""
import argparse
import os
import re
import shutil
from pathlib import Path

# (old node, new node, label for a colliding "Project Memory - Personal.md")
MOVES = [
    ("Plex & Home Networking", "Servers + Media Stack + Home Networking", None),
    ("Servers",                "Servers + Media Stack + Home Networking", "ESC4000 G3"),
    ("ESP32 + HA",             "ESP32 + Embedded Sensors",                None),
    ("3D Printing",            "3D Printing + Fabrication",               None),
]

SUBDIRS = ["Chats/Full Transcripts", "Chats/Raw", "Chats/Attachments", "Chats", "Project Files"]


def merge_dir(src: Path, dst: Path, dry: bool, log):
    """Move everything from src into dst, never overwriting."""
    for item in sorted(src.rglob("*")):
        if item.is_dir():
            continue
        rel = item.relative_to(src)
        target = dst / rel
        if target.exists():
            log(f"     [skip, exists] {rel}")
            continue
        log(f"     {rel}")
        if not dry:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(item), str(target))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", default=os.environ.get("VAULT_ROOT", "/vault"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    vault = Path(args.vault)
    dry = args.dry_run
    log = print

    if not vault.is_dir():
        raise SystemExit(f"!! vault not found: {vault}")

    print(f"{'(dry run) ' if dry else ''}Reorganizing {vault}\n")

    # ---------------------------------------------------------------- move
    for old, new, mem_label in MOVES:
        src, dst = vault / old, vault / new
        if not src.is_dir():
            print(f"-- {old!r}: no such node, skipping")
            continue
        if src == dst:
            continue

        # A colliding memory dossier gets relabelled rather than dropped.
        if mem_label:
            for m in list(src.glob("Project Memory*.md")):
                renamed = src / f"Project Memory - {mem_label}.md"
                if m.name != renamed.name and not renamed.exists():
                    print(f"   relabel {m.name} -> {renamed.name}")
                    if not dry:
                        m.rename(renamed)

        # The old index is regenerated under the new name; drop it.
        for idx in src.glob("* \u2014 Index.md"):
            print(f"   drop generated index {idx.name}")
            if not dry:
                idx.unlink()

        if dst.exists():
            print(f"MERGE {old!r} -> {new!r}")
            merge_dir(src, dst, dry, log)
            if not dry:
                shutil.rmtree(src, ignore_errors=True)
        else:
            print(f"RENAME {old!r} -> {new!r}")
            if not dry:
                src.rename(dst)
        print()

    # ---------------------------------------------------------------- relink
    print("Rewriting links ...")
    # longest names first, so "Plex & Home Networking" isn't half-matched by a
    # shorter overlapping name
    pairs = sorted({(o, n) for o, n, _ in MOVES if o != n}, key=lambda p: -len(p[0]))
    changed = 0
    for f in vault.rglob("*.md"):
        if "\\.obsidian\\" in str(f):
            continue
        try:
            text = orig = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for old, new in pairs:
            o, n = re.escape(old), new.replace("\\", "\\\\")
            # [[<any ../ prefix><Old> — Index|<Old>]]  and  |← <Old> index]]
            text = re.sub(rf'({o}) \u2014 Index\|{o}\]\]', f'{n} \u2014 Index|{n}]]', text)
            text = re.sub(rf'({o}) \u2014 Index\|\u2190 {o} index\]\]',
                          f'{n} \u2014 Index|\u2190 {n} index]]', text)
            text = re.sub(rf'\[\[{o}/{o} \u2014 Index\\\|{o}\]\]',
                          f'[[{n}/{n} \u2014 Index\\|{n}]]', text)
        if text != orig:
            changed += 1
            if not dry:
                f.write_text(text, encoding="utf-8", newline="\n")
    print(f"  {changed} file(s) relinked")

    print("\nDone. Now run:  py -3 reindex.py --vault \"%s\"" % vault)


if __name__ == "__main__":
    main()
